name: CI – Cucumber + Playwright
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:20   # ⬅️ pakai image resmi Node 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps & browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Sanity: paths & versions
        run: |
          node -v
          npm -v
          npx cucumber-js --version
          echo "== tree =="
          ls -la
          echo "== support =="
          ls -la features/support || true
          echo "== steps =="
          ls -la features/steps || true

      - name: Run Cucumber (write JUnit)
        run: |
          mkdir -p results
          set -o pipefail
          npm run bdd | tee cucumber.log
        # kalau kamu ingin build tetap merah saat gagal, biarkan seperti ini (tanpa || true)

      - name: Ensure results exists (placeholder if crashed)
        if: always()
        run: |
          if [ ! -f results/cucumber.xml ]; then
            echo "Cucumber didn’t produce JUnit, creating placeholder for visibility"
            cat > results/cucumber.xml <<'XML'
            <testsuite name="cucumber" tests="1" failures="1">
              <testcase classname="ci" name="Cucumber failed to start">
                <failure>Check 'Run Cucumber' step logs in Actions</failure>
              </testcase>
            </testsuite>
XML
          fi

      - name: Upload logs & JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-artifacts
          path: |
            cucumber.log
            results/*.xml
