name: Playwright (BDD)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: playwright-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers (CLI)
        run: npx playwright install --with-deps

      - name: Generate BDD tests
        run: npm run bddgen

      - name: Ensure results dir (JUnit)
        run: mkdir -p results

      - name: Run Playwright tests
        env:
          # ganti jika perlu: staging/sandbox/prod
          BASE_URL: https://demoblaze.com
        run: npm test

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/**
          retention-days: 14

      - name: Upload JUnit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: results/**
          retention-days: 14
